name: Deploy to Droplet

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 143.110.225.104 >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh root@143.110.225.104 << 'EOF'
          cd ~/reveal-socket
          git pull origin main
          npm install
          pm2 restart reveal-socket
        EOF
